// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1:string):Promise<string>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetOverdueTasks():Promise<string>;

export function GetTask(arg1:string):Promise<string>;

export function GetTasks(arg1:string):Promise<string>;

export function GetTasksByPriority(arg1:number):Promise<string>;

export function GetTasksByStatus(arg1:number):Promise<string>;

export function ToggleTaskStatus(arg1:string):Promise<string>;

export function UpdateTask(arg1:string):Promise<string>;
