// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetOverdueTasks() {
  return window['go']['main']['App']['GetOverdueTasks']();
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTasks(arg1) {
  return window['go']['main']['App']['GetTasks'](arg1);
}

export function GetTasksByPriority(arg1) {
  return window['go']['main']['App']['GetTasksByPriority'](arg1);
}

export function GetTasksByStatus(arg1) {
  return window['go']['main']['App']['GetTasksByStatus'](arg1);
}

export function ToggleTaskStatus(arg1) {
  return window['go']['main']['App']['ToggleTaskStatus'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}
